- name: delete dir
  ansible.builtin.file:
    path: "{{ app_location }}"   
    state: absent

- name: createe dir
  ansible.builtin.file:
    path: "{{ app_location }}"   
    state: directory   

- name: Unarchive or unzip
  ansible.builtin.unarchive:
    src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip
    dest: "{{ app_location }}"
    remote_src: yes